### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by xh9998** [ShaoTengLiu/Video-P2P#10]
OSError: Can't load tokenizer for '/cpfs01/user/lixiaohui/code/Video-P2P/outputs/rabbitjump'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'Video-P2P/outputs/rabbitjump' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.

**Comment by ShaoTengLiu** [comment]
Could you share your running scripts?

The default saving location is outputs/rabbit-jump. Did you correctly save your weights in outputs/rabbitjump?

**Comment by xh9998** [comment]
yes,I do.  I change it to jump rabbit. I try another yaml but still got this error. Let me show you:

python run_videop2p.py --config="configs/man-motor-p2p.yaml"
Traceback (most recent call last):
  File "/cpfs01/user/lixiaohui/code/Video-P2P/run_videop2p.py", line 664, in <module>
    main(**OmegaConf.load(args.config), fast=args.fast)
  File "/cpfs01/user/lixiaohui/code/Video-P2P/run_videop2p.py", line 75, in main
    tokenizer = CLIPTokenizer.from_pretrained(pretrained_model_path, subfolder="tokenizer")
  File "/cpfs01/user/lixiaohui/.conda/envs/TAV/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1825, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for './outputs/man-motor'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure './outputs/man-motor' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.

**Comment by xh9998** [comment]
<img width="319" alt="image" src="https://github.com/ShaoTengLiu/Video-P2P/assets/97648549/f438005b-1783-42a5-b0f0-739c6447fd7e">
I have got ddim_latent-500.pt, isnt that enough?

**Comment by ShaoTengLiu** [comment]
Does
python run_videop2p.py --config="configs/rabbit-jump-p2p.yaml" --fast
work for you?

**Comment by ShaoTengLiu** [comment]
If you run the first stage (run_tuning.py) properly. There should be outputs/rabbit-jump/tokenizer

**Comment by xh9998** [comment]
ok, thank you. It turns out that the question lies in tuneavideo.
TypeError: The keyword `fps` is no longer supported. Use `duration`(in ms) instead, e.g. `fps=50` == `duration=20` (1000 * 1/50). 
Afer I fix this, I get the right tokenizer.

**Comment by ShaoTengLiu** [comment]
Thanks for pointing out.
