### ISSUE TITLE
cannot import name 'cached_download' from 'huggingface_hub'

### ISSUE THREAD

**Issue by x2x5** [ShaoTengLiu/Video-P2P#18]
I followed the default setting and got this problem.

I tried to solve it by use

```
pip install huggingface-hub==0.25.2
```

and solved it

**Comment by kimlemon1** [comment]
When I install 0.25.2 version, now another error occurs
                                                                                                                                                                                                                             
python run_tuning.py  --config="configs/rabbit-jump-tune.yaml"                                                                                                                                                                            
                                                                                                                                                                                                                                           
ImportError: huggingface-hub>=0.30.0,<1.0 is required for a normal functioning of this module, but found huggingface-hub==0.25.2.                                                                                                                                           
Try: `pip install transformers -U` or `pip install -e '.[dev]'` if you're working with git main  `

It seems huggingface-hub must be >=0.30.0 but >=0.26.0 occurs "cached_download" error.

Did you saw this error?
