### ISSUE TITLE
Complete dataset

### ISSUE THREAD

**Issue by Muhammad4hmed** [ShaoTengLiu/Video-P2P#2]
Hi, 

Thank you for sharing the code. I was wondering if you will release the complete data on which the model was trained on because the dataset you shared [here](https://drive.google.com/drive/folders/1EN501LLVg4FPeZ39lEBYHdXrs7nc5wDb) contains only the testing data.

Thanks

**Comment by ShaoTengLiu** [comment]
Hi,

The data shared [here](https://drive.google.com/drive/folders/1EN501LLVg4FPeZ39lEBYHdXrs7nc5wDb) is the complete data.

Since our method is a one-shot method, there is not training-testing split. Thanks,
