### ISSUE TITLE
The use of config

### ISSUE THREAD

**Issue by Laidawang** [ShaoTengLiu/Video-P2P#3]
hi,
I am so amazed at your work,But I still have doubts about some parameters in config p2p.I want to know the specific role of blend_word and eq_params.

for EX. 
  - "authentic style, a man is driving a motorbike in the forest"
  - "cartoon style, a Iron-Man is driving a motorbike in the river"
 How should I set these two items?

thx

**Comment by ShaoTengLiu** [comment]
Hi,

1. The **blend_word** determines the [attention mask](https://github.com/ShaoTengLiu/Video-P2P/blob/92d2b52a636385bbbeff632523a934f5c7c9462f/run_videop2p.py#L122), which is described in our paper's Alg. 1 line 11.
2. The **eq_params** is used [here](https://github.com/ShaoTengLiu/Video-P2P/blob/04e444e865d1a97676a0e37935eddbf09d6389d0/run_videop2p.py#L382) for re-weighting, as discussed in paper's section 4.2 (Attention re–weighting).
3. For more details, you can also refer to [prompt-to-prompt](https://github.com/google/prompt-to-prompt).
4. In your first example, you can set the blend_word to None and eq_params to {'words': 'authentic', 'values': 5}. Please refer to this [config](https://github.com/ShaoTengLiu/Video-P2P/blob/main/configs/bird-forest-p2p.yaml).
5. In your second example, there are two kinds of changes. One is word swap and another is prompt refinement (global). I think our code structure doesn't support it at this moment. However, you can try to modify some codes [here](https://github.com/ShaoTengLiu/Video-P2P/blob/92d2b52a636385bbbeff632523a934f5c7c9462f/run_videop2p.py#L371) to complete two changes sequentially.

Thanks.

**Comment by Laidawang** [comment]
Your explanation is so detailed, I really appreciate it.Thank you!
