### ISSUE TITLE
How to calculate quantitative metrics

### ISSUE THREAD

**Issue by shliu0** [ShaoTengLiu/Video-P2P#5]
Hi,
I am really appreciate your excellent work.
Could you please tell more details about how you calculate theses metrics? 
the paper demonstrate 4 different quantitative metrics(3 proposed before, 1 proposed in your paper) and said can find details in appendix, however, I can't find the appendix. I am wondering if you can tell more details about how to calculate them. e.g. what is the mask in M.PSNR, how to calculate PSNR(averaged PSNR of R,G,B channel or take RGB as a whole then divided by 3?) the version you use for LPIPS, averaged frame LPIPS to represent video LPIPS?, the definition of OSV, etc. 

Thanks

**Comment by ShaoTengLiu** [comment]
Please refer:
<img width="618" alt="appendix_1" src="https://user-images.githubusercontent.com/51499992/232988339-a187b4e2-ddb0-411d-983d-5e3898b0dfb3.png">
<img width="623" alt="appendix_2" src="https://user-images.githubusercontent.com/51499992/232988359-dd8fb9e0-278b-4774-ac7b-7efb7cb24f03.png">

**Comment by JulianJuaner** [comment]
Hi,
1. In eq(14), M.PSNR is calculated between **unchanged** regions (background) as we need to ensure the unrelated regions are unchanged after the editing.
2. You are right, in eq(15), * us of size(n, c). The variance is calculated among the frame dimension (n), and we sum the variance in each channel as the OSV result.

**Comment by shliu0** [comment]
> > Thanks a lot! Two more questions to make sure I understand correctly: 1、PSNR is calculated between changed object regions instead of background? 2、Var(*) for shortly in eq(15), * is of size (n, c)? then how to calculate this variance?
> 
> Hi,
> 
> 1. In eq(14), M.PSNR is calculated between **unchanged** regions (background) as we need to ensure the unrelated regions are unchanged after the editing.
> 2. You are right, in eq(15), * is of size(n, c). The variance is calculated among the frame dimension (n), and we sum the variance in each channel as the OSV result.
