### ISSUE TITLE
 have a error MODEL_LIBRARY_ORG_NAME

### ISSUE THREAD

**Issue by videoprice** [ShaoTengLiu/Video-P2P#6]
Hi I have a error with python app_gradio.py
 "Traceback (most recent call last):
  File "D:\Video-P2P\app_gradio.py", line 14, in <module>
    from gradio_utils.app_training import create_training_demo
  File "D:\Video-P2P\gradio_utils\app_training.py", line 9, in <module>
    from constants import MODEL_LIBRARY_ORG_NAME, SAMPLE_MODEL_REPO, UploadTarget
ImportError: cannot import name 'MODEL_LIBRARY_ORG_NAME' from 'constants' (C:\ProgramData\Anaconda3\envs\p2p\lib\site-packages\constants.py)"

**Comment by ShaoTengLiu** [comment]
I think it is well defined [here](https://github.com/ShaoTengLiu/Video-P2P/blob/92d2b52a636385bbbeff632523a934f5c7c9462f/gradio_utils/constants.py#L9).

You can check **"C:\ProgramData\Anaconda3\envs\p2p\lib\site-packages\constants.py"** to see whether it is the same as [this](https://github.com/ShaoTengLiu/Video-P2P/blob/main/gradio_utils/constants.py).

**Comment by ShaoTengLiu** [comment]
I will temporally close this issue. You are welcome to reopen it if you still have this problem.
