### ISSUE TITLE
The problem with rabbit-jump-p2p.yaml

### ISSUE THREAD

**Issue by jiajiaxiaoskx** [ShaoTengLiu/Video-P2P#9]
Hi, I have a problem with rabbit-jump-p2p.yaml.
After I train the model using rabbit-jump-tune.yaml, the fine-tuned checkpoint is stored in the output folder, and when I use rabbit-jump-tune.yaml to edit the video, what the road should I use in  pretrained_model_path config(line 1), since there are two folders (stable-diffusion-v1.5 and output) I have to load the model.
Thanks for answering!

**Comment by ShaoTengLiu** [comment]
You need to use rabbit-jump-p2p.yaml to edit. Thanks.

**Comment by jiajiaxiaoskx** [comment]
Sorry for the mistake I made, I did use rabbit-jump-p2p.yaml and I'm confused about the route of pretrained model I should use. It seems the choice of checkpointing_steps and so on in the rabbit-jump-tune.yaml influence the save of output fine-tuned model. Could you please share the accurate parameters (checkpointing_steps, validation_steps, max_train_steps) in rabbit-jump-p2p.yaml, and the proper route of pretrained_model_path used in edit?
Thanks a lot!

**Comment by ShaoTengLiu** [comment]
Hi, in your logs, I only see some warnings. Can you clarify your problem and show me your running script?

**Comment by jiajiaxiaoskx** [comment]
**It seems that the problem may lie in run_videop2p.py in the** 

with torch.no_grad():
-->        sequence = ldm_stable(
            prompts,
            generator=generator,
            latents=x_t,
            uncond_embeddings_pre=uncond_embeddings,
            controller = controller,
            video_length=video_len,
            fast=fast,
        ).videos
    sequence1 = rearrange(sequence[0], "c t h w -> t h w c")
    sequence2 = rearrange(sequence[1], "c t h w -> t h w c")
    inversion = []
    videop2p = []

**the pixel values in sequence are all nan, making it impossible to generate the accurate gif file.**

the config file I used is as follows:
pretrained_model_path: "./outputs/rabbit-jump"
image_path: "./data/rabbit"
prompt: "a rabbit is jumping on the grass"
prompts:
  - "a rabbit is jumping on the grass"
  - "a origami rabbit is jumping on the grass"
blend_word:
  - 'rabbit'
  - 'rabbit'
eq_params:
  words:
    - "origami"
  values:
    - 2
save_name: "origami"
is_word_swap: False

Thanks a lot!

**Comment by ShaoTengLiu** [comment]
Dose python run_videop2p.py --config="configs/rabbit-jump-p2p.yaml" --fast works for you?

**Comment by ShaoTengLiu** [comment]
I will temporally close this issue. You are welcome to reopen it if you still have this problem.
